# Generated by Django 5.0.7 on 2024-08-03 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_venta_detalleventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.EmailField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 8, 3, 12, 16, 22, 691045)),
        ),
    ]
